# Generated by Django 5.1.1 on 2024-10-07 12:27

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_contactmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Category name'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Category name'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
